### ISSUE TITLE
Beginner Friendly Issue - Correct Spelling Freelance

### ISSUE THREAD

**Issue by wimpywarlord** [wimpywarlord/wimpywarlord.github.io#5]
🚫DISCLAIMER🚫
Don't consider this as a contribution towards your hacktoberfest challenge. This is a practice PR. So that you get familiar with the process of sending PRs.

A good list of issues can be found on the following two links.

https://github.com/vinitshahdeo/Hacktoberfest2021

https://github.com/wimpywarlord/Hacktober-Wimpy-Style/blob/main/Issues/issues.md

Hi,

👉  So I think you found this issue from the Beginner-friendly issues list, and you are just getting started with Open Source.

👉  This is a perfect opportunity to get your hand dirty, and not get overwhelmed at the same time. 

👉 I have deliberately introduced a bug into my website. 

💕 Problem 

The Spelling for freelance on my [website](https://kshitijdhyani.com/) contains a necessary space in between the word. 

![Screenshot_4](https://user-images.githubusercontent.com/41532804/135167185-1ff3c5e9-acac-4849-89e4-6d5706113c52.png)

Kindly help me fix this 🥺.

💕Assistance

It's under the index.html file. 

Inside the Work-Ex modal.

 💕How to contribute.
 
 Send a PR, and I review it. If it's up to the mark, I will approve it and merge it to the main codebase. 
 
 Learn how to send a PR [here](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

**Comment by Niyati3031** [comment]
@wimpywarlord Can you please assign me this for Hacktoberfest 21..

**Comment by wimpywarlord** [comment]
Hi @Niyati3031 

Sure go ahead.

**Comment by thunderfreak** [comment]
Hi, I've fixed the issue and sent a PR. Kindly review

**Comment by alfaniM** [comment]
Hello, Can you please assign me this for Hacktoberfest 21. This is my first year participating in the event

**Comment by wimpywarlord** [comment]
> Hi, I've fixed the issue and sent a PR. Kindly review

Hi @thunderfreak,

Cant merge your PR now, since October is yet to start. 

Good work though. 

I suggest if you have gotten a fair idea about git now, try to contribute to a medium or hard level issue now.

Good luck

**Comment by wimpywarlord** [comment]
> Hello, Can you please assign me this for Hacktoberfest 21. This is my first year participating in the event

Hi @alfaniM,

You can start working on the bug, irrespective of the assignment. 

The main idea is to learn git and not worry about assignments. 

Even if I don't merge your PR, you will still learn the whole process. 

So go ahead and give it a shot and don't worry about an assignment for now.

**Comment by jigarvyasidea** [comment]
Can you please assign me this for Hacktoberfest 21..

**Comment by wimpywarlord** [comment]
The issue has been assigned to @akarsh1263, his PR has been merged and the issue is now being closed.
